version: "3.7"
services:
  api:
    restart: always
    build:
      context: .
      target: production
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 4000:4000
    command: node ./src/index.js