# Use postgres/example user/password credentials
version: '3.7'

volumes:
  db:
    driver: local

services:
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - "3000:8080"

  #master-data-config:
  #  restart: always
  #  image: master-data-config
  #  depends_on:
  #    - db
  #  ## build:
  #  ##   context: ./master-data-config/
  #  ##   target: staging
  #  ## volumes:
  #  ##   - ./:/app
  #  ##   - /app/node_modules
  #  ports:
  #   - 4000:4000
  #  command: node ./src/index.js

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    #to connect ==> $ psql --host=localhost --port=5432 --username=admin --password