version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app/
      - dependencies:/usr/src/app/node_modules
    working_dir: /usr/src/app
    environment:
      NODE_ENV: staging
    ports:
      - 4000:4000
    command: npm run staging
volumes:
  dependencies: